/*
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.micro_lang


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MicroLangStandaloneSetup extends MicroLangStandaloneSetupGenerated {

	def static void doSetup() {
		new MicroLangStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
