/*
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.micro_lang.parser.antlr;

import dk.sdu.mdsd.micro_lang.parser.antlr.internal.InternalMicroLangParser;
import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;

public class MicroLangTokenSource extends AbstractIndentationTokenSource {

	public MicroLangTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		return token.getType() == InternalMicroLangParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		return InternalMicroLangParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		return InternalMicroLangParser.RULE_END;
	}

}
